services:
  smsservice.api:
    image: smsservice.api
    container_name: sms-service-api
    build:
      context: ..
      dockerfile: SmsService/SmsService.API/Dockerfile
    environment:
      - Kafka__SendSmsEvent__BootstrapServers=kafka-notification:9092
      - Kafka__ErrorSmsEvent__BootstrapServers=kafka-notification:9092
      - Kafka__ApproveSmsEvent__BootstrapServers=kafka-notification:9092

      - SmsOptions__ApiId=api 
      - SmsOptions__Url=http://mock-notification-service:8080/notifications/sms
    networks:
      - notification-network
    
networks:
  notification-network:
    external: true
