services:
  mock-api:
    image: wiremock/wiremock:latest
    container_name: mock-notification-service
    volumes:
      - ./mappings:/home/wiremock/mappings
    restart: always
    networks:
      - notification-network
    
networks:
  notification-network:
    external: true